import { pool } from "./pool.js";

const skills = [
  { name: "Python", category: "Technical", difficulty: 2 },
  { name: "JavaScript", category: "Technical", difficulty: 2 },
  { name: "TypeScript", category: "Technical", difficulty: 3 },
  { name: "Java", category: "Technical", difficulty: 3 },
  { name: "C#", category: "Technical", difficulty: 3 },
  { name: "C++", category: "Technical", difficulty: 4 },
  { name: "SQL", category: "Technical", difficulty: 2 },
  { name: "NoSQL Databases", category: "Technical", difficulty: 3 },
  { name: "Data Analysis", category: "Technical", difficulty: 3 },
  { name: "Data Visualization", category: "Technical", difficulty: 3 },
  { name: "Machine Learning", category: "Technical", difficulty: 4 },
  { name: "Statistics", category: "Academic", difficulty: 3 },
  { name: "Cloud Computing", category: "Technical", difficulty: 3 },
  { name: "AWS", category: "Technical", difficulty: 3 },
  { name: "Azure", category: "Technical", difficulty: 3 },
  { name: "GCP", category: "Technical", difficulty: 3 },
  { name: "Docker", category: "Technical", difficulty: 3 },
  { name: "Kubernetes", category: "Technical", difficulty: 4 },
  { name: "Linux", category: "Technical", difficulty: 3 },
  { name: "Networking", category: "Technical", difficulty: 3 },
  { name: "Cybersecurity", category: "Technical", difficulty: 4 },
  { name: "DevOps", category: "Technical", difficulty: 4 },
  { name: "CI/CD", category: "Technical", difficulty: 3 },
  { name: "System Design", category: "Technical", difficulty: 4 },
  { name: "API Design", category: "Technical", difficulty: 3 },
  { name: "REST APIs", category: "Technical", difficulty: 2 },
  { name: "GraphQL", category: "Technical", difficulty: 3 },
  { name: "Testing Automation", category: "Technical", difficulty: 3 },
  { name: "Mobile Development", category: "Technical", difficulty: 3 },
  { name: "iOS Development", category: "Technical", difficulty: 4 },
  { name: "Android Development", category: "Technical", difficulty: 4 },
  { name: "Frontend Development", category: "Technical", difficulty: 3 },
  { name: "Backend Development", category: "Technical", difficulty: 3 },
  { name: "Full-Stack Development", category: "Technical", difficulty: 4 },
  { name: "UI Design", category: "Creative", difficulty: 3 },
  { name: "UX Design", category: "Creative", difficulty: 3 },
  { name: "UX Research", category: "Creative", difficulty: 3 },
  { name: "Graphic Design", category: "Creative", difficulty: 3 },
  { name: "Product Design", category: "Creative", difficulty: 3 },
  { name: "Copywriting", category: "Communication", difficulty: 3 },
  { name: "Content Strategy", category: "Communication", difficulty: 3 },
  { name: "SEO", category: "Business", difficulty: 3 },
  { name: "Digital Marketing", category: "Business", difficulty: 3 },
  { name: "Paid Advertising", category: "Business", difficulty: 3 },
  { name: "Social Media", category: "Communication", difficulty: 2 },
  { name: "Brand Strategy", category: "Business", difficulty: 3 },
  { name: "Market Research", category: "Business", difficulty: 3 },
  { name: "Product Management", category: "Leadership", difficulty: 3 },
  { name: "Project Management", category: "Leadership", difficulty: 3 },
  { name: "Program Management", category: "Leadership", difficulty: 4 },
  { name: "Agile Methodology", category: "Leadership", difficulty: 2 },
  { name: "Scrum", category: "Leadership", difficulty: 2 },
  { name: "Kanban", category: "Leadership", difficulty: 2 },
  { name: "Stakeholder Management", category: "Leadership", difficulty: 3 },
  { name: "Roadmapping", category: "Leadership", difficulty: 3 },
  { name: "Business Analysis", category: "Business", difficulty: 3 },
  { name: "Finance", category: "Business", difficulty: 3 },
  { name: "Accounting", category: "Business", difficulty: 3 },
  { name: "Sales", category: "Business", difficulty: 3 },
  { name: "Negotiation", category: "Communication", difficulty: 3 },
  { name: "Customer Success", category: "Communication", difficulty: 3 },
  { name: "Public Speaking", category: "Communication", difficulty: 3 },
  { name: "Technical Writing", category: "Communication", difficulty: 3 },
  { name: "Documentation", category: "Communication", difficulty: 2 },
  { name: "Leadership", category: "Leadership", difficulty: 3 },
  { name: "People Management", category: "Leadership", difficulty: 4 },
  { name: "Coaching", category: "Leadership", difficulty: 3 },
  { name: "Mentoring", category: "Leadership", difficulty: 3 },
  { name: "Conflict Resolution", category: "Communication", difficulty: 3 },
  { name: "Problem Solving", category: "Soft skills", difficulty: 3 },
  { name: "Critical Thinking", category: "Soft skills", difficulty: 3 },
  { name: "Adaptability", category: "Soft skills", difficulty: 2 },
  { name: "Time Management", category: "Soft skills", difficulty: 2 },
  { name: "Teamwork", category: "Soft skills", difficulty: 2 },
  { name: "Creativity", category: "Creative", difficulty: 2 },
  { name: "Innovation", category: "Creative", difficulty: 3 },
  { name: "Strategy", category: "Business", difficulty: 4 },
  { name: "Operations", category: "Business", difficulty: 3 },
  { name: "Supply Chain", category: "Business", difficulty: 3 },
  { name: "HR Management", category: "Business", difficulty: 3 },
  { name: "Recruiting", category: "Business", difficulty: 3 },
  { name: "Training", category: "Leadership", difficulty: 3 },
  { name: "Business Development", category: "Business", difficulty: 3 },
  { name: "Customer Research", category: "Business", difficulty: 3 },
  { name: "Presentation Design", category: "Creative", difficulty: 2 },
  { name: "Data Engineering", category: "Technical", difficulty: 4 },
  { name: "ETL Pipelines", category: "Technical", difficulty: 4 },
  { name: "Data Warehousing", category: "Technical", difficulty: 4 },
  { name: "Big Data", category: "Technical", difficulty: 4 },
  { name: "AI Ethics", category: "Academic", difficulty: 3 },
  { name: "Mathematics", category: "Academic", difficulty: 3 },
  { name: "Economics", category: "Academic", difficulty: 3 },
  { name: "Research Methods", category: "Academic", difficulty: 3 },
  { name: "Psychology", category: "Academic", difficulty: 3 },
  { name: "Biology", category: "Academic", difficulty: 3 },
  { name: "Chemistry", category: "Academic", difficulty: 3 },
  { name: "Physics", category: "Academic", difficulty: 4 },
  { name: "Healthcare Knowledge", category: "Academic", difficulty: 3 },
  { name: "Clinical Research", category: "Academic", difficulty: 4 },
  { name: "Laboratory Skills", category: "Technical", difficulty: 3 },
  { name: "CAD", category: "Technical", difficulty: 3 },
  { name: "Electrical Engineering", category: "Technical", difficulty: 4 },
  { name: "Mechanical Engineering", category: "Technical", difficulty: 4 },
  { name: "Civil Engineering", category: "Technical", difficulty: 4 },
  { name: "Architecture", category: "Creative", difficulty: 4 },
  { name: "Construction Management", category: "Business", difficulty: 3 },
  { name: "Quality Assurance", category: "Technical", difficulty: 3 },
  { name: "Risk Management", category: "Business", difficulty: 3 },
  { name: "Compliance", category: "Business", difficulty: 3 },
  { name: "Legal Research", category: "Academic", difficulty: 3 },
  { name: "Policy Analysis", category: "Academic", difficulty: 3 },
  { name: "Teaching", category: "Communication", difficulty: 3 },
  { name: "Instructional Design", category: "Creative", difficulty: 3 },
  { name: "Curriculum Development", category: "Academic", difficulty: 3 },
  { name: "Event Planning", category: "Business", difficulty: 2 },
  { name: "Logistics", category: "Business", difficulty: 2 },
  { name: "Customer Service", category: "Communication", difficulty: 2 },
  { name: "Writing", category: "Communication", difficulty: 2 },
  { name: "Editing", category: "Communication", difficulty: 2 },
  { name: "Translation", category: "Communication", difficulty: 3 },
  { name: "Photography", category: "Creative", difficulty: 3 },
  { name: "Video Production", category: "Creative", difficulty: 3 },
  { name: "Animation", category: "Creative", difficulty: 3 },
  { name: "3D Modeling", category: "Creative", difficulty: 4 },
  { name: "Game Design", category: "Creative", difficulty: 4 },
  { name: "Music Production", category: "Creative", difficulty: 3 },
  { name: "Performing Arts", category: "Creative", difficulty: 3 },
  { name: "Culinary Skills", category: "Trade", difficulty: 2 },
  { name: "Welding", category: "Trade", difficulty: 3 },
  { name: "Electrical Work", category: "Trade", difficulty: 3 },
  { name: "Plumbing", category: "Trade", difficulty: 3 },
  { name: "Carpentry", category: "Trade", difficulty: 3 },
  { name: "Automotive Repair", category: "Trade", difficulty: 3 },
  { name: "Machining", category: "Trade", difficulty: 4 },
  { name: "HVAC", category: "Trade", difficulty: 3 },
  { name: "First Aid", category: "Physical", difficulty: 2 },
  { name: "Safety Training", category: "Physical", difficulty: 2 },
  { name: "Physical Fitness", category: "Physical", difficulty: 2 },
  { name: "Athletic Coaching", category: "Physical", difficulty: 3 },
  { name: "Nursing", category: "Academic", difficulty: 4 }
];

async function seedSkills() {
  for (const skill of skills) {
    await pool.query(
      `INSERT INTO skills (name, category, difficulty, description)
       VALUES ($1, $2, $3, $4)
       ON CONFLICT (name) DO NOTHING`,
      [skill.name, skill.category, skill.difficulty, null]
    );
  }
}

seedSkills()
  .then(() => {
    console.log(`Seeded ${skills.length} skills.`);
    return pool.end();
  })
  .catch((error) => {
    console.error("Skill seed failed", error);
    pool.end();
  });
